### ISSUE TITLE
Support nested JSON format for downstream KR&R 

### ISSUE THREAD

**Issue by saraswat** [gabrielStanovsky/props#11]
For knowledge representation and reasoning tasks, it is valuable to represent the information in a sentence in some kind of nested attribute value form. I am working on such a form in my fork. Here are [some examples](https://github.com/saraswat/props/blob/master/examples.md). The core idea is to nest a form x into the representation of the first node y from which there is a link rel to x, and use `xref`/`xlink` fields to represent other linkages. 

In general, the "KR" aspects of Props needs further development, in my opinion. (I see a lot of emphasis in the project on visualization.)

Please let me know if there is some interest in a pull request. (I will have to do some refactoring since I have also committed modifications necessary to run on MacOS, will need to pull them out.) Note: currently working to add information from features into the representation.

**Comment by gabrielStanovsky** [comment]
Is this a duplicate of #10?

**Comment by saraswat** [comment]
duplicate
