### ISSUE TITLE
Getting refactor_dep_parsing to work

### ISSUE THREAD

**Issue by mfeblowitz** [gabrielStanovsky/props#18]
Hi, Gabriel - I'm working with @saraswat, looking specifically at getting the props refactor_dep_parsing branch to work (on a Mac).

The current run issue I'm seeing is  this:

Upon running the sample run command ```python props/applications/parse_props.py sample.json -t --oie --corenlp-json-input``` python shows this response:

```Traceback (most recent call last):
  File "props/applications/parse_props.py", line 29, in <module>
    import run
  File "/Users/mfeb/tmp/props_corenlp/props/props/applications/run.py", line 1, in <module>
    from props.dependency_tree.tree_readers import read_trees_file, read_dep_graphs_file
ImportError: No module named props.dependency_tree.tree_readers
```

Surprising, as the file is in the expected location. I'm using  python 2.7.13 under anaconda on the mac, the same version that runs the master branch with @saraswats's adjustments for running on a mac.

Other  issues/questions:

1. it turned out I had to ```pip uninstall props```  to remove the prior version of props, which was masking access to the new version of parseSentences (arity 3).

2. It appears that one needs to separately install Stanford Core NLP (not stated in the quick install instructions) 

3. README.md for props states a Java prerequisite of 1.7, but the Core NLP code requires 1.8 - will this create issues ? Or is the 1.7 requirement an artifact of using the Berkeley parser?

**Comment by gabrielStanovsky** [comment]
Hi Mark, 

Can you try running with a clean [virtualenv](https://virtualenv.pypa.io/en/stable/userguide/) environment?
(That way we can make sure it's not the old installation getting in the way of this one).

Specifically, if you can try the following, it would be great:
```bash
virtualenv .venv
source .venv/bin/activate
pip install -r ./props/install/requirements.txt
python props/applications/parse_props.py sample.json -t --oie --corenlp-json-input
```
This works on my ubuntu machine.

Per your points:

1. I think that this should be covered by using virtualenv
2. That's true, I'll add that to the quick install.
3. Yes, that's just a prerequisite of Berkeley, so you can ignore that. 

Thanks!

**Comment by gabrielStanovsky** [comment]
Edit regarding point 2 - the quick install says:

> We supply a pipeline script to interact with the CORENLP parser, **assuming it is already installed**, and that the CORENLP_HOME environment variable points to the CORENLP home folder containing all its jars.

Do you think I should phrase that differently?
Thanks!

**Comment by mfeblowitz** [comment]
Sounds good.

Thanks,

Mark

**Comment by mfeblowitz** [comment]
Gabriel - 
I tried installing a vanilla virtualenv under anaconda but the two don't seem to play well together. Instead I used [this](https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/) to set up a virtual environment on conda. 

Got the same result: ```No module named props.dependency_tree.tree_readers``` I even tried uninstalling all of the dependencies and starting with a fresh clone of props/refactor_dep_parsing.

A mystery.

I'll try it on a Linux machine.

**Comment by mfeblowitz** [comment]
Ok. It took quite a bit of work, but I was able to get the new pipeline running.

The extra work was because the anaconda docker container is built on a very minimal debian image. So, to get it to a point were all parts worked required:

1. installing java 8 (and all that entails)
2. retrieving and unpacking CoreNLP 
3. installing "build-essential", which brings in g++, c++, etc.
4. retrieving the wordnet corpora
5. retrieving and installing props

I'll be boiling this down to a set of instructions and will post them.

I still don't understand why the same doesn't work on the Mac. It appears to be the same version of python (2.7.13). It's seems to be something with references to python module *cousins* (children of  parents' siblings). I'll try a few things.

**Comment by gabrielStanovsky** [comment]
Thanks for putting in the effort and documenting the process!

> Got the same result: No module named props.dependency_tree.tree_readers I even tried uninstalling all of the dependencies and starting with a fresh clone of props/refactor_dep_parsing.

A guess about this - is it possible that your PYTHONPATH environment variable doesn't include the current directory? Can you please compare its value between the two platforms?

Thanks again!

**Comment by mfeblowitz** [comment]
That was a very good guess. Not sure why PYTHONPATH is needed on the Mac and not on Linux. Maybe another security-related prohibition?  You might want to consider adding a note in the installation instructions about Macs and  PYTHONPATH.

So, I can now verify that this branch works on both the mac and on debian, including  the pipeline script.

There are still issues with the "Full Installation (with Berkeley Parser)", reflected in @saraswat's fork. The main issues are 1) the use of "sed -i", not supported on the Mac, and 2) the need to push "/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/" into  setup.py of JPype. The set of patches can be  seen in  commit [42f63e7](https://github.com/saraswat/props/commit/42f63e77abce7852feb8a090bc19782a06e4a42e) which is a set of quick fixes to support mac installation (but might  not reflect not a pushable general fix).

Thanks for your help and for addressing the pipeline simplification.

**Comment by gabrielStanovsky** [comment]
Great! Happy to hear that it now works on both platforms.

> There are still issues with the "Full Installation (with Berkeley Parser)"

I think that the new simplified pipeline was the correct way to go to begin with, which allows users to plug in their own dependency parses, as long as they conform to CORENLP's json format. Thanks @saraswat for suggesting that!

@saraswat's fork also contains a very useful json representation output for PropS which you may find more convenient.
Although he may need to first pull these changes to allow the json representation to work with the pipeline output.

I guess I can go ahead and close this issue?

**Comment by mfeblowitz** [comment]
Yes, please.
